trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTaskRunnerInstaller@0
  inputs:
    nodeVersion: '10'

- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    containerRegistry: 'Course_B9MG119'  
    repository: 'B9MG119/todolist'
    command: 'buildAndPush'
    Dockerfile: '**/app/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(Build.BuildId)
      latest
